/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_test_ndk_MyJni */

#ifndef _Included_com_example_test_ndk_MyJni
#define _Included_com_example_test_ndk_MyJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_test_ndk_MyJni
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_test_ndk_MyJni_stringFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
